[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "DRO"
version = "0.1.0"
description = "Code for DRO project"
requires-python = ">=3.13"
readme = "README.md"
dependencies = [
    "cvxpy==1.6.7",
    "dsp-cvxpy==0.4.2",
    "numpy",
    "scipy>=1.15",
    "scikit-learn",
    "h5py",
    "matplotlib",
    "pytest",
]

[tool.pytest.ini_options]
testpaths = ["tests"]
pythonpath = ["src"]

[tool.setuptools.packages.find]
where = ["src"]
